name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.x'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk

  analyze-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.x'
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter format --set-exit-if-changed .

  deploy:
    needs: [build-and-test, analyze-and-format]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.x'
    - run: flutter pub get
    - run: flutter build appbundle
    - uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: build/app/outputs/bundle/release/*.aab
